# Generated by Django 5.2.17 on 2026-09-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150)),
                ('points_claimed', models.IntegerField(default=0)),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='academic_portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='InternalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('series_1_marks', models.FloatField(default=0.0)),
                ('series_2_marks', models.FloatField(default=0.0)),
                ('assignment_marks', models.FloatField(default=0.0)),
                ('attendance_marks', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='academic_portal.student')),
            ],
        ),
    ]
